"""add content_hash to repository_files

Revision ID: dfe08a8d0c48
Revises: 22efac4e8b9a
Create Date: 2026-08-04 21:40:47.040219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe08a8d0c48'
down_revision: Union[str, Sequence[str], None] = '22efac4e8b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository_files', sa.Column('content_hash', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository_files', 'content_hash')
    # ### end Alembic commands ###
