"""add repository files and scan summary fields

Revision ID: 22efac4e8b9a
Revises: 5bcdb3404ba3
Create Date: 2026-08-03 12:58:21.110951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22efac4e8b9a'
down_revision: Union[str, Sequence[str], None] = '5bcdb3404ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('extension', sa.String(length=50), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_files_id'), 'repository_files', ['id'], unique=False)
    op.create_index(op.f('ix_repository_files_repository_id'), 'repository_files', ['repository_id'], unique=False)
    op.add_column('repositories', sa.Column('total_files', sa.Integer(), nullable=True))
    op.add_column('repositories', sa.Column('total_directories', sa.Integer(), nullable=True))
    op.add_column('repositories', sa.Column('total_size_bytes', sa.Integer(), nullable=True))
    op.add_column('repositories', sa.Column('language_breakdown', sa.JSON(), nullable=True))
    op.add_column('repositories', sa.Column('key_files', sa.JSON(), nullable=True))
    op.add_column('repositories', sa.Column('scan_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'scan_completed_at')
    op.drop_column('repositories', 'key_files')
    op.drop_column('repositories', 'language_breakdown')
    op.drop_column('repositories', 'total_size_bytes')
    op.drop_column('repositories', 'total_directories')
    op.drop_column('repositories', 'total_files')
    op.drop_index(op.f('ix_repository_files_repository_id'), table_name='repository_files')
    op.drop_index(op.f('ix_repository_files_id'), table_name='repository_files')
    op.drop_table('repository_files')
    # ### end Alembic commands ###
