"""add file knowledge

Revision ID: e586525d4db6
Revises: dfe08a8d0c48
Create Date: 2026-08-11 12:32:23.103808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e586525d4db6'
down_revision: Union[str, Sequence[str], None] = 'dfe08a8d0c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_file_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('imports', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_file_id'], ['repository_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_knowledge_id'), 'file_knowledge', ['id'], unique=False)
    op.create_index(op.f('ix_file_knowledge_repository_file_id'), 'file_knowledge', ['repository_file_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_knowledge_repository_file_id'), table_name='file_knowledge')
    op.drop_index(op.f('ix_file_knowledge_id'), table_name='file_knowledge')
    op.drop_table('file_knowledge')
    # ### end Alembic commands ###
