"""add file analysis counts

Revision ID: ea7f4b293ac1
Revises: 31e9b52000c5
Create Date: 2026-08-22 13:26:23.372431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea7f4b293ac1'
down_revision: Union[str, Sequence[str], None] = '31e9b52000c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('analyzed_files_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('repositories', sa.Column('failed_files_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('repositories', sa.Column('skipped_files_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'skipped_files_count')
    op.drop_column('repositories', 'failed_files_count')
    op.drop_column('repositories', 'analyzed_files_count')
    # ### end Alembic commands ###
