"""add repository summary

Revision ID: 6ea7d559d674
Revises: ea7f4b293ac1
Create Date: 2026-08-22 21:24:22.489839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ea7d559d674'
down_revision: Union[str, Sequence[str], None] = 'ea7f4b293ac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('repo_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'repo_summary')
    # ### end Alembic commands ###
