"""create repositories table

Revision ID: 5bcdb3404ba3
Revises: d17723345566
Create Date: 2026-07-22 22:09:02.136676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bcdb3404ba3'
down_revision: Union[str, Sequence[str], None] = 'd17723345566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('GIT', 'UPLOAD', name='source_type'), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SCANNING', 'EMBEDDING', 'READY', 'FAILED', name='repository_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_id'), 'repositories', ['id'], unique=False)
    op.create_index(op.f('ix_repositories_owner_id'), 'repositories', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repositories_owner_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_id'), table_name='repositories')
    op.drop_table('repositories')
    # Autogenerate doesn't drop enum types on its own - clean these up manually
    sa.Enum(name='repository_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='source_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
